version: "3"
services:
  run:
    build:
      context: .
      dockerfile: ./docker/blog/Dockerfile
      target: run
    container_name: blog-run-dev
    depends_on:
      - stub-esa-api
    ports:
      - 3000:3000
    environment:
      JSON_SERVER_HOST: http://stub-esa-api:3000
    volumes:
      - .:/src/essay
      - /src/essay/node_modules
  unit:
    build:
      context: .
      dockerfile: ./docker/blog/Dockerfile
      target: test
    container_name: blog-unit-test
    depends_on:
      - stub-esa-api
    environment:
      JSON_SERVER_HOST: http://stub-esa-api:3000
    volumes:
      - .:/src/essay
      - /src/essay/node_modules
  stub-esa-api:
    build:
      context: .
      dockerfile: ./docker/json-server/Dockerfile
    volumes:
      - ./docker/json-server/:/src/json-server
    command: json-server -w data.js -r routes.json -m auth.js -H 0.0.0.0
    ports:
      - 3030:3000
    restart: always
